# Generated by Django 3.2.12 on 2022-04-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(default=33, verbose_name='возраст'),
        ),
    ]
